# Generated by Django 3.2.8 on 2021-10-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(blank=True, choices=[('B', 'Buy'), ('H', 'Hold'), ('S', 'Sell')], default=True, max_length=4, null=True),
        ),
    ]
